### ISSUE TITLE
Dynamic Facet

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#13]
@NightOwl888 
Can BoboBrowse.Net let me build dynamic facets ([see here](http://www.slideshare.net/lucenerevolution/lsr-dublin-lucenefacetserera) slide 11)?

**Comment by NightOwl888** [comment]
Yes, BoboBrowse.Net supports adding dynamic facet handlers.

There are [several built in facet handlers](https://github.com/NightOwl888/BoboBrowse.Net/wiki/Prebuilt-Facet-Handler-Types#prebuilt-runtime-facet-handlers) that implement [RuntimeFacetHandler](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Net/Facets/RuntimeFacetHandler.cs). These handlers can be added at runtime using the BoboBrowser.SetFacetHandler() method as demonstrated in the [TestTime unit test](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Tests/BoboTestCase.cs#L2692).

**Comment by dtosato** [comment]
Ben dai!

Diego Tosato
Product Development Team

diego.tosato@eurosystem.it<mailto:franco.brunello@eurosystem.it>
+39 0422 628.878
Eurosystem S.p.a.
[cid:image001.png@01D0686E.63B93DC0]

www.eurosystem.it<http://www.eurosystem.it>

www.freewayskyline.it<http://www.freewayskyline.it>

[cid:image002.png@01D0686E.63B93DC0]<https://twitter.com/#!/twitteurosystem>  [cid:image003.png@01D0686E.63B93DC0] <https://www.facebook.com/eurosystemspa>   [cid:image004.png@01D0686E.63B93DC0] <https://www.linkedin.com/company/eurosystem>   [cid:image005.png@01D0686E.63B93DC0] <http://www.youtube.com/user/freewayskyline>





IMPORTANTE! Dal 1 gennaio 2015 tutte le aziende del Gruppo Eurosystem Sistemarca Srl sono entrate a far parte di Eurosystem S.p.a. Per maggiori informazioni contattateci.

INFORMAZIONI STRETTAMENTE CONFIDENZIALI L'invio di questa e-mail è destinato solo ad uso personale o a enti sopra nominati e potrebbe contenere informazioni riservate, coperte da segreto professionale, e non soggette a divulgazione ai sensi di legge. Se non ne siete i corretti destinatari, con la presente siete informati che non vi è assolutamente permessa alcuna divulgazione, copia, distribuzione, o altro uso delle informazioni in essa contenute. Se per errore avete ricevuto questo messaggio, Vi chiedo cortesemente di informarmi immediatamente al mio indirizzo di posta elettronica. Grazie

Da: Shad Storhaug [mailto:notifications@github.com]
Inviato: giovedì 26 marzo 2015 19:00
A: NightOwl888/BoboBrowse.Net
Cc: Tosato Diego
Oggetto: Re: [BoboBrowse.Net] Dynamic Facet (#13)


Yes, BoboBrowse.Net supports adding dynamic facet handlers.

There are several built in facet handlers<https://github.com/NightOwl888/BoboBrowse.Net/wiki/Prebuilt-Facet-Handler-Types#prebuilt-runtime-facet-handlers> that implement RuntimeFacetHandler<https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Net/Facets/RuntimeFacetHandler.cs>. These handlers can be added at runtime using the BoboBrowser.SetFacetHandler() method as demonstrated in the TestTime unit test<https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Tests/BoboTestCase.cs#L2692>.
