### ISSUE TITLE
NullReferenceException in GetFacets

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#14]
@NightOwl888 
Probably I found a bug in `BoboBrowse.Net.Facets.CombinedFacetAccessible.GetFacets()`. It gives me back a `System.NullReferenceException` extracting the collection of `BrowseFacet` for this handler:
```c#
BoboBrowse.Net.Facets.Impl.RangeFacetHandler(name, new BoboBrowse.Net.Facets.Data.PredefinedTermListFactory<int>(), values);
```
where `values` is composed as follows:
```c#
"[0000000000 TO 0000001000]"	
"[0000001000 TO 0000010000]"	
"[0000010000 TO 0000100000]"	
"[0000100000 TO 0001000000]"	
"[0001000000 TO *]"	
```
Could you please check?
Thanks.

**Comment by NightOwl888** [comment]
Thanks for the report.

I [added a unit test](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Tests/FacetRangeTest.cs#L357) calling the same overload with the same values, but was unable to reproduce the null reference exception.

Could you check this against your code and build another unit test that throws the exception?

**Comment by dtosato** [comment]
I found the bug which is in BoboBrowse.Net.Facets.CombinedFacetAccessible.GetFacets():
![Bug into GetFacets](https://dl.dropboxusercontent.com/u/20825744/tmp/boboError.PNG)
As you can see from the image the null variable in your code is rootFacet.

I have already spent several hours, but it is still not clear its reason, however:
- it does not depend on the type of the handler;
- it does not depend on the number of results (the bug appears with 0 results as with N);
- it does not depend on the type of query;
- it does not depend on the output specs;
- it does not depend on the browse selections;
- it does not depend on the data (i.e., the lucene index).

Could you please check?

**Comment by dtosato** [comment]
Finally, [here a sample](https://dl.dropboxusercontent.com/u/20825744/tmp/GetFacetsTest.zip).

**Comment by NightOwl888** [comment]
FYI - I confirmed this is a bug and created a patch in the latest version, [3.2.2](https://github.com/NightOwl888/BoboBrowse.Net/releases/tag/v3.2.2).  I also added a [new test](https://github.com/NightOwl888/BoboBrowse.Net/blob/master/src/BoboBrowse.Net/BoboBrowse.Tests/BoboTestCase.cs#L1517) for this specific scenario to the `BoboTestCase.TestFacetSort()` method.
