### ISSUE TITLE
NullReferenceException when parallel searching 

### ISSUE THREAD

**Issue by dtosato** [NightOwl888/BoboBrowse.Net#23]
Hi @NightOwl888,
[In this sample of code](https://dl.dropboxusercontent.com/u/20825744/tmp/BoboNullRef.zip) I get a NullReferenceException when bobo is used for parallel searching.
Could you check if it is possible to change the NullReferenceException with a specific type of exception?

**Comment by NightOwl888** [comment]
Hello,

I gave your project a try, but I am not getting any exceptions. I am guessing this has something to do with a difference in processor architecture. I have a quad-core I7 processor (2.2Ghz) (4702MQ), what kind of processor are you seeing this null reference exception on?
